/*
 * @Author: GlennLiu <glennliu0607@gmail.com>
 * @Date: {{.Date}}
 * @LastEditors: Glenn 18322653727@163.com
 * @LastEditTime: 2025-10-28 16:16:35
 * @FilePath: \glennctl\api\gogen\types.tpl
 * @Description:
 *		glennctl {{.version}}
 *		Code generated by glennctl. DO NOT EDIT.
 * Copyright (c) 2025 by 天津晟源士兴科技有限公司, All Rights Reserved.
 */

package types{{if .containsTime}}
import (
	"time"
){{end}}
{{.types}}
